application: siagile
version: 1
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: .*
  static_files: index.html
  upload: index.html
